[lattice]
lx = 64
ly = 64

[chain]
bond_energy = 0.0
delta_f = 0.0
delta_mu = 0.0
eta = 1.0
lambda = 100.0
scheme = "negative_drive"

[initial_condition]
density = 0.025
bonding_fraction = 0.5

[simulation]
equilibration_time = 1000.0
chunk_time = 100.0
num_chunks = 100
seed = 42

[output]
outdir = "results/test0"
